### ISSUE TITLE
Typo3 v12 package?

### ISSUE THREAD

**Issue by sunixzs** [crazy252/typo3_vite#2]
Hey crazy252.

Really nice extension 👍 - thx.

I would like to use it in a Typo3 version 12 environment and couldn't find a matching version of this extension. So I just cloned your package into the project and changed the requirement in `composer.json` to 12 and the constraint in `ext_tables.php` to 12.

It seems the extension is running with v12 out of the box.

I would kindly ask if you can publish a v12 package to packagist.org.

Thanks in advance.

**Comment by sunixzs** [comment]
1000 thx, crazy252, for the fast update.

I just added v1.1.1 from packagist by using composer.

There is a small problem in Typo3 v12. The constant `TYPO3_MODE` does not exist anymore. Now it's just called `TYPO3`. So in `ext_tables.php` and `ext_localconf.php` the line `defined('TYPO3_MODE') || die('Access denied.');` stops the CMS.

For v11 and v12 in combination it may should be:

```php
if (!(defined('TYPO3_MODE') || defined('TYPO3'))) {
    die('Access denied.');
}
```

Best regards, sun

**Comment by crazy252** [comment]
Thanks for the solution. I hope that it now works without problems

**Comment by boecko** [comment]
Hi ..  the solution is wrong
It should be

```php
if (!defined('TYPO3_MODE') && !defined('TYPO3')) {
    die('Access denied.');
}
```

Only when both are not defined there should be an error.
