### ISSUE TITLE
Typo3 v12 compatibility issue

### ISSUE THREAD

**Issue by sunixzs** [crazy252/typo3_vite#4]
Hi crazy252,

me again with a small request :)

The definition of the static template file in `ext_tables.php` leads to a warning in the install tool.

In Typo3 v12 go to Admin-Tools -> Upgrade -> Check Extension Compatibility. Then this message is shown:

![Screenshot 2023-10-12 at 06 11 07](https://github.com/crazy252/typo3_vite/assets/15161027/9ee86f73-cf1e-4827-b83a-adbaff8ca525)

The solution is to remove `ext_tables.php` and move the contents to:

**typo3_vite/Configuration/TCA/Overrides/sys_template.php**

```php
<?php

declare(strict_types=1);

use TYPO3\CMS\Core\Utility\ExtensionManagementUtility;

ExtensionManagementUtility::addStaticFile(
    'typo3_vite',
    'Configuration/TypoScript',
    'TYPO3 Vite'
);
```

Thx in advance and best regards

sunixzs :-)

BTW: `ext_localconf.php` has no function and IMO this file can be removed also.

**Comment by crazy252** [comment]
Hi,

thanks for the issue. It should be fixed with the new version.

I hope everything works now as expected.
